language: erlang

# Try using multiple Lua Implementations
env:
  - LUA_VERSION='5.1' LUA="lua5.1"
  - LUA_VERSION='5.1' LUA="luajit" # Wee need to install lua5.1 or luarocks won't build
  - LUA_VERSION='5.2' LUA="lua5.2"
  - LUA_VERSION='5.3' LUA="lua"

branches:
  only:
    - master

install:
  - test "$LUA_VERSION" = "5.3" || sudo apt-get install lua$LUA_VERSION liblua$LUA_VERSION-dev
  - test "$LUA" = "luajit" && git clone http://luajit.org/git/luajit-2.0.git && cd luajit-2.0/ && sudo make install && cd .. || true
  - test "$LUA_VERSION" = "5.3" && wget http://www.lua.org/ftp/lua-5.3.0.tar.gz && tar xzf lua-5.3.0.tar.gz && cd lua-5.3.0 && make linux && sudo make install && cd .. || true
  - sudo apt-get --no-install-recommends install doxygen
  - git clone git://github.com/keplerproject/luarocks.git
  - cd luarocks
  - ./configure --lua-version=$LUA_VERSION --versioned-rocks-dir
  - make build
  - sudo make install  
  - cd ..
  # Install testing dependency
  - sudo luarocks-$LUA_VERSION install lut
  # Build module
  - sudo luarocks-$LUA_VERSION make

# Run tests
script:
  - $LUA -v && $LUA test/all.lua

notifications:
  recipients:
    - gaspard@teti.ch
  email:
    on_success: change
    on_failure: always
